name: CD workflow

on:                 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
         pip install nose
         nosetests -v --with-spec --spec-color --with-coverage --cover-package=service

      #- name: Set up QEMU
       # uses: docker/setup-qemu-action@v2
      
      #- name: Set up Docker Buildx
       # uses: docker/setup-buildx-action@v2

      
      - name: Login to Docker Hub
        uses: zemuldo/docker-build-push@master
        with:
          args: $(secrets.DOCKERHUB_USERNAME) , $(secrets.DOCKERHUB_TOKEN)
      








        