name: CD workflow

on:                 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3  

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: |
         pip install nose
         nosetests -v --with-spec --spec-color --with-coverage --cover-package=service
      
      - name: Login and build to Docker Hub
        uses: zemuldo/docker-build-push@master
        env:
         DOCKER_USERNAME: "hbrigitte"
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         REGISTRY_URL: "docker.io"
        with:
          image_name: "bree"
          image_tag: latest

       
          API_KEY: ${{ secrets.API_KEY }}
          INSTALL_PLUGINS: code-engine,container-service
          REGION: eu-de
          RESOURCE_GROUP: solutions

      - name: Instal IBM Cloud CLI
        uses: dprosper/ic-setup-cli@v0.1.2
        with:
          API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          INSTALL_PLUGINS: code-engine,container-service
          REGION: eu-de
          RESOURCE_GROUP: Default

      - name: Log in to IBM Cloud
        run: |
         ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} --no-region
         ibmcloud target -g default

      #- name: Set up IBM Cloud Kubernetes
        #uses: IBM/github-actions/setup-ibm-cloud-kubernetes@v1

      - name: Retrieve Docker Hub image
        run: docker pull bree:latest

      - name: Build and push Docker image to IBM Cloud Container Registry
        run: |
         docker build -t your-ibm-registry-image:tag .
         docker login -u ${{ secrets.IBM_CLOUD_CONTAINER_REGISTRY_USERNAME }} -p ${{ secrets.IBM_CLOUD_CONTAINER_REGISTRY_API_KEY }} mycluster.icr.io
         docker tag your-ibm-registry-image:tag mycluster.icr.io/your-namespace/your-ibm-registry-image:tag
         docker push mycluster.icr.io/your-namespace/your-ibm-registry-image:tag

      - name: Deploy to Kubernetes
        run: |
         kubectl apply -f deployment.yaml
         kubectl apply -f service.yaml