name: CI workflow 
on:
  push:
    branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  build:
     runs-on: ubuntu-latest
     container: python:3.9-slim
     steps:
       - name: Check out
         uses: actions/checkout@v3
        
       - name: install dependencies
         run: | 
          python -m pip install --upgrade pip
          


       - name: Lint with flake8
         run: |
          pip install flake8
          
          
       - name: Run unit tests with nose
         run: 
           nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
           
    
