name: CI workflow 
on:
  push:
    branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  build:
     runs-on: ubuntu-latest
     container: python:3.9-slim
     steps:
       - name: Check out
         uses: actions/checkout@v3
        
       - name: install dependencies
         run: | 
          python -m pip install --upgrade pip setuptools wheel
          python -m venv tutorial-env
          source tutorial-env/bin/activate
          pip install -r /usr/local/lib/python3.9/site-packages requirements.txt

       

       - name: Run unit tests with nose
         run: 
           nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
           


          


